import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
export default function Post({ posts }) {
  // const router = useRouter({ posts });
  // console.log(posts);
  return (
    <div>
      <Head>
        <title>Home Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>hello from Post</div>
      {/* <button
        onClick={() => {
          router.push({
            pathname: "/post/[id]",
            query: { id: 1 },
          });
        }}
      >
        read more
      </button> */}
      {posts.map((ele, idx) => {
        return (
          <li key={idx}>
            <Link href={`post/ssr/${ele.id}`}>{ele.title}</Link>
          </li>
        );
      })}
      {/* <Link href={"/"}>Home</Link> */}
    </div>
  );
}

export async function getStaticProps() {
  const data = await fetch("https://jsonplaceholder.typicode.com/posts");
  const posts = await data.json();
  // console.log(posts);

  return {
    props: {
      posts,
    },
  };
}
