import Head from "next/head";
import Link from "next/link";
const Login = () => {
  return (
    <div>
      <Head>
        <title>Home Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>hello from Login</div>
      <Link href={"/"}>
        <a>Home</a>
      </Link>
    </div>
  );
};

export default Login;
